### ISSUE TITLE
pip version 1.3.0 error when collapse = False

### ISSUE THREAD

**Issue by dloyola** [fpusan/moira#3]
Hello,
today when i tried to use the pip version for correcting reads I realized that if you don't want to get the output collapsed the software fail, I was checking the code in github version and there are somo lines to validate the 'collpase' option that there are not in pip version.
I think that would be great if you can fix it, because there are a lot of pip users.
great software!

David

**Comment by fpusan** [comment]
I actually thought I had made it available, I've been having troubles when submitting things to pip lately. It should be fixed now, just upgrade the package with pip.
